AXF/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from App import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url('^$', views.index),
    url('^app/', include('App.urls',namespace='app')),
]

App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url('^home/', views.home,name='home'),
    url('^market/', views.market,name='market'),
    url('^cart/', views.cart,name='cart'),
    url('^mine/', views.mine,name='mine'),
]

App/models.py
from django.db import models

# Create your models here.

App/views.py
from django.shortcuts import render, redirect


# Create your views here.
from django.urls import reverse


def index(request):
    return redirect(reverse('app:home'))

def home(request):
    return render(request,'home.html')


def market(request):
    return render(request, 'market.html')


def cart(request):
    return render(request, 'cart.html')


def mine(request):
    return render(request, 'mine.html')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>首页</title>
    <link href="{% static 'css/reset.css' %}" rel="stylesheet">
    <style type="text/css">
        .header {
            height: 60px;
            background-color: #A9A9A9;
            left: 0;
            top: 0;
        }

        .header, .footer {
            width: 100%;
            position: fixed;
        }

        .header h3 {
            text-align: center;
            line-height: 60px;
        }

        .content {
            height: 1000px;
            text-align: center;
            padding-top: 100px;
        }

        .footer {
            height: 60px;
            background-color: white;
            bottom: 0;
            left: 0;
        }
    </style>
</head>
<body>

<div class="header">
    {% block header%}
        <h3>请填充标题</h3>
    {% endblock %}

</div>

<div class="content">

    {% block content %}
        请填充内容
    {% endblock %}


</div>
<div class="footer">

    <a href="{% url 'app:home' %}">
        <img src="{% static 'img/home.png' %}">
        <span>首页</span>
    </a>
    <a href="{% url 'app:market' %}">
        <img src="{% static 'img/market.png' %}">
        <span>闪购</span>
    </a>
    <a href="{% url 'app:cart' %}">
        <img src="{% static 'img/cart.png' %}">
        <span>购物车</span>
    </a>
    <a href="{% url 'app:mine' %}">
        <img src="{% static 'img/mine.png' %}">
        <span>我的</span>
    </a>

</div>

</body>
</html>

templates/cart.html
{% extends 'base.html' %}

{% block header %}
<h3>购物车</h3>
{% endblock %}

{% block content %}
 购物车内容区域
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block header %}
    <h3>首页</h3>
{% endblock %}

{% block content %}
    首页内容区域
{% endblock %}

templates/market.html
{% extends 'base.html' %}

{% block header %}
<h3>闪购</h3>
{% endblock %}

{% block content %}
 闪购内容区域
{% endblock %}

templates/mine.html
{% extends 'base.html' %}

{% block header %}
<h3>个人中心</h3>
{% endblock %}

{% block content %}
 个人中心内容区域
{% endblock %}